# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  terraformVersion : '1.1.5'
  system.debug: 'true'
stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildCode
    pool:
      vmImage: 'windows-latest'
    steps:

    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore      
        projects: '**/*.csproj'
        
    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        projects: $(solution)
        arguments: ' --no-restore --configuration $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      displayName: 'Run Publish'
      inputs:
        projects: '**/*.csproj'
        command: publish
        publishWebProjects: false
        zipAfterPublish: true
        arguments: ' --no-build --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
      condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))  
   